import { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { supabase } from "@/integrations/supabase/client";

// Supported languages with native names
export const LANGUAGES = [
  { code: "en", name: "English", nativeName: "English", dir: "ltr" },
  { code: "ur", name: "Urdu", nativeName: "اردو", dir: "rtl" },
  { code: "ar", name: "Arabic", nativeName: "العربية", dir: "rtl" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", dir: "ltr" },
  { code: "es", name: "Spanish", nativeName: "Español", dir: "ltr" },
  { code: "fr", name: "French", nativeName: "Français", dir: "ltr" },
  { code: "de", name: "German", nativeName: "Deutsch", dir: "ltr" },
  { code: "zh", name: "Chinese", nativeName: "中文", dir: "ltr" },
  { code: "pt", name: "Portuguese", nativeName: "Português", dir: "ltr" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", dir: "ltr" },
  { code: "ru", name: "Russian", nativeName: "Русский", dir: "ltr" },
  { code: "ja", name: "Japanese", nativeName: "日本語", dir: "ltr" },
  { code: "ko", name: "Korean", nativeName: "한국어", dir: "ltr" },
  { code: "it", name: "Italian", nativeName: "Italiano", dir: "ltr" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", dir: "ltr" },
  { code: "pl", name: "Polish", nativeName: "Polski", dir: "ltr" },
  { code: "th", name: "Thai", nativeName: "ไทย", dir: "ltr" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", dir: "ltr" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", dir: "ltr" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu", dir: "ltr" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", dir: "ltr" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", dir: "ltr" },
  { code: "fa", name: "Persian", nativeName: "فارسی", dir: "rtl" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili", dir: "ltr" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", dir: "ltr" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", dir: "ltr" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", dir: "ltr" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", dir: "ltr" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", dir: "ltr" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", dir: "ltr" },
  { code: "uk", name: "Ukrainian", nativeName: "Українська", dir: "ltr" },
  { code: "ro", name: "Romanian", nativeName: "Română", dir: "ltr" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά", dir: "ltr" },
  { code: "cs", name: "Czech", nativeName: "Čeština", dir: "ltr" },
  { code: "sv", name: "Swedish", nativeName: "Svenska", dir: "ltr" },
  { code: "hu", name: "Hungarian", nativeName: "Magyar", dir: "ltr" },
  { code: "he", name: "Hebrew", nativeName: "עברית", dir: "rtl" },
  { code: "fi", name: "Finnish", nativeName: "Suomi", dir: "ltr" },
  { code: "no", name: "Norwegian", nativeName: "Norsk", dir: "ltr" },
  { code: "da", name: "Danish", nativeName: "Dansk", dir: "ltr" },
];

// Translation keys and their values
type TranslationKey = keyof typeof translations.en;

const translations = {
  en: {
    // Navigation
    dashboard: "Dashboard",
    newInvoice: "New Invoice",
    inventory: "Inventory",
    salesHistory: "Sales History",
    credits: "Credits",
    creditManagement: "Credit Management",
    receivePayment: "Receive Payment",
    expenses: "Expenses",
    customers: "Customers",
    manageWorkers: "Manage Workers",
    settings: "Settings",
    logout: "Logout",
    collapse: "Collapse",
    
    // Common
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    add: "Add",
    search: "Search",
    filter: "Filter",
    export: "Export",
    import: "Import",
    loading: "Loading...",
    noData: "No data found",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    submit: "Submit",
    reset: "Reset",
    close: "Close",
    view: "View",
    print: "Print",
    download: "Download",
    upload: "Upload",
    select: "Select",
    all: "All",
    none: "None",
    yes: "Yes",
    no: "No",
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    completed: "Completed",
    
    // Settings
    generalSettings: "General Settings",
    receiptSettings: "Receipt Settings",
    languageSettings: "Language & Timezone Settings",
    profileSettings: "Profile Settings",
    appName: "Application Name",
    appDescription: "Application Description",
    uploadLogo: "Upload Logo",
    shopName: "Shop Name",
    shopAddress: "Shop Address",
    ownerNames: "Owner Names",
    addOwnerName: "Add Owner Name",
    phoneNumbers: "Phone Numbers",
    addPhoneNumber: "Add Phone Number",
    thankYouMessage: "Thank You Message",
    footerMessage: "Footer Message",
    workerName: "Worker Name (Shown on Receipt)",
    workerPhone: "Worker Phone (Shown on Receipt)",
    selectLanguage: "Select Language",
    selectTimezone: "Select Timezone",
    saveGeneralSettings: "Save General Settings",
    saveReceiptSettings: "Save Receipt Settings",
    saveSettings: "Save Settings",
    saveProfile: "Save Profile",
    
    // Profile
    fullName: "Full Name",
    email: "Email",
    phoneNumber: "Phone Number",
    
    // Invoice
    items: "Items",
    total: "Total",
    invoiceDate: "Invoice date",
    paymentMethod: "Payment method",
    cash: "Cash",
    card: "Card",
    online: "Online",
    credit: "Credit",
    discount: "Discount",
    paidAmount: "Paid amount (Optional)",
    fullPayment: "Full payment",
    leaveEmptyForFullPayment: "Leave empty for full payment",
    saveAndPrint: "Save & Print",
    customerName: "Customer Name",
    customerPhone: "Customer Phone",
    selectProduct: "Select product",
    quantity: "Quantity",
    price: "Price",
    subtotal: "Subtotal",
    netTotal: "Net Total",
    totalCost: "Total cost",
    totalProfit: "Total profit",
    finalTotal: "Final Total",
    paid: "Paid",
    due: "Due",
    
    // Inventory
    addProduct: "Add Product",
    productName: "Product Name",
    category: "Category",
    purchasePrice: "Purchase Price",
    sellingPrice: "Selling Price",
    stockQuantity: "Stock Quantity",
    quantityType: "Quantity Type",
    supplier: "Supplier",
    sku: "SKU",
    description: "Description",
    lowStock: "Low Stock",
    outOfStock: "Out of Stock",
    inStock: "In Stock",
    
    // Credits
    addCredit: "Add Credit",
    creditAmount: "Credit Amount",
    remainingAmount: "Remaining Amount",
    dueDate: "Due Date",
    status: "Status",
    notes: "Notes",
    paymentReceived: "Payment Received",
    markAsPaid: "Mark as Paid",
    
    // Customers
    addCustomer: "Add Customer",
    customerDetails: "Customer Details",
    totalPurchases: "Total Purchases",
    lastPurchase: "Last Purchase",
    
    // Expenses
    addExpense: "Add Expense",
    expenseType: "Expense Type",
    amount: "Amount",
    date: "Date",
    rent: "Rent",
    utilities: "Utilities",
    salaries: "Salaries",
    supplies: "Supplies",
    other: "Other",
    
    // Workers
    addWorker: "Add Worker",
    workerDetails: "Worker Details",
    permissions: "Permissions",
    role: "Role",
    admin: "Admin",
    worker: "Worker",
    
    // Dashboard
    todaySales: "Today's Sales",
    weeklySales: "Weekly Sales",
    monthlySales: "Monthly Sales",
    totalCustomers: "Total Customers",
    totalProducts: "Total Products",
    pendingCredits: "Pending Credits",
    topProducts: "Top Products",
    topCustomers: "Top Customers",
    recentSales: "Recent Sales",
    salesOverview: "Sales Overview",
    profitOverview: "Profit Overview",
    
    // Messages
    savedSuccessfully: "Saved successfully!",
    deletedSuccessfully: "Deleted successfully!",
    errorOccurred: "An error occurred",
    confirmDelete: "Are you sure you want to delete?",
    noPermission: "You do not have permission for this action",
    
    // Receipt
    billNo: "Bill No",
    invoiceNo: "Invoice No",
    item: "Item",
    qty: "Qty",
    
    // Time
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    custom: "Custom",
    
    // Actions
    actions: "Actions",
    moreOptions: "More Options",
  },
  ur: {
    // Navigation
    dashboard: "ڈیش بورڈ",
    newInvoice: "نیا انوائس",
    inventory: "انوینٹری",
    salesHistory: "فروخت کی تاریخ",
    credits: "ادھار",
    creditManagement: "ادھار مینجمنٹ",
    receivePayment: "ادائیگی وصول کریں",
    expenses: "اخراجات",
    customers: "گاہک",
    manageWorkers: "ورکرز منیج کریں",
    settings: "ترتیبات",
    logout: "لاگ آؤٹ",
    collapse: "سمیٹیں",
    
    // Common
    save: "محفوظ کریں",
    cancel: "منسوخ",
    delete: "حذف کریں",
    edit: "ترمیم",
    add: "شامل کریں",
    search: "تلاش",
    filter: "فلٹر",
    export: "برآمد",
    import: "درآمد",
    loading: "لوڈ ہو رہا ہے...",
    noData: "کوئی ڈیٹا نہیں ملا",
    confirm: "تصدیق",
    back: "واپس",
    next: "اگلا",
    submit: "جمع کریں",
    reset: "ری سیٹ",
    close: "بند کریں",
    view: "دیکھیں",
    print: "پرنٹ",
    download: "ڈاؤن لوڈ",
    upload: "اپ لوڈ",
    select: "منتخب کریں",
    all: "سب",
    none: "کوئی نہیں",
    yes: "ہاں",
    no: "نہیں",
    active: "فعال",
    inactive: "غیر فعال",
    pending: "زیر التواء",
    completed: "مکمل",
    
    // Settings
    generalSettings: "عمومی ترتیبات",
    receiptSettings: "رسید کی ترتیبات",
    languageSettings: "زبان اور ٹائم زون کی ترتیبات",
    profileSettings: "پروفائل کی ترتیبات",
    appName: "ایپ کا نام",
    appDescription: "ایپ کی تفصیل",
    uploadLogo: "لوگو اپ لوڈ کریں",
    shopName: "دکان کا نام",
    shopAddress: "دکان کا پتہ",
    ownerNames: "مالکان کے نام",
    addOwnerName: "مالک کا نام شامل کریں",
    phoneNumbers: "فون نمبرز",
    addPhoneNumber: "فون نمبر شامل کریں",
    thankYouMessage: "شکریہ کا پیغام",
    footerMessage: "فٹر پیغام",
    workerName: "ورکر کا نام (رسید پر)",
    workerPhone: "ورکر کا فون (رسید پر)",
    selectLanguage: "زبان منتخب کریں",
    selectTimezone: "ٹائم زون منتخب کریں",
    saveGeneralSettings: "عمومی ترتیبات محفوظ کریں",
    saveReceiptSettings: "رسید کی ترتیبات محفوظ کریں",
    saveSettings: "ترتیبات محفوظ کریں",
    saveProfile: "پروفائل محفوظ کریں",
    
    // Profile
    fullName: "پورا نام",
    email: "ای میل",
    phoneNumber: "فون نمبر",
    
    // Invoice
    items: "اشیاء",
    total: "کل",
    invoiceDate: "انوائس کی تاریخ",
    paymentMethod: "ادائیگی کا طریقہ",
    cash: "نقد",
    card: "کارڈ",
    online: "آن لائن",
    credit: "ادھار",
    discount: "رعایت",
    paidAmount: "ادا کی گئی رقم (اختیاری)",
    fullPayment: "مکمل ادائیگی",
    leaveEmptyForFullPayment: "مکمل ادائیگی کے لیے خالی چھوڑیں",
    saveAndPrint: "محفوظ کریں اور پرنٹ کریں",
    customerName: "گاہک کا نام",
    customerPhone: "گاہک کا فون",
    selectProduct: "پروڈکٹ منتخب کریں",
    quantity: "مقدار",
    price: "قیمت",
    subtotal: "ذیلی کل",
    netTotal: "خالص کل",
    totalCost: "کل لاگت",
    totalProfit: "کل منافع",
    finalTotal: "حتمی کل",
    paid: "ادا شدہ",
    due: "واجب الادا",
    
    // Inventory
    addProduct: "پروڈکٹ شامل کریں",
    productName: "پروڈکٹ کا نام",
    category: "زمرہ",
    purchasePrice: "خرید قیمت",
    sellingPrice: "فروخت قیمت",
    stockQuantity: "اسٹاک مقدار",
    quantityType: "مقدار کی قسم",
    supplier: "سپلائر",
    sku: "SKU",
    description: "تفصیل",
    lowStock: "کم اسٹاک",
    outOfStock: "اسٹاک ختم",
    inStock: "اسٹاک میں",
    
    // Credits
    addCredit: "ادھار شامل کریں",
    creditAmount: "ادھار کی رقم",
    remainingAmount: "باقی رقم",
    dueDate: "آخری تاریخ",
    status: "حالت",
    notes: "نوٹس",
    paymentReceived: "ادائیگی موصول",
    markAsPaid: "ادا شدہ کریں",
    
    // Customers
    addCustomer: "گاہک شامل کریں",
    customerDetails: "گاہک کی تفصیلات",
    totalPurchases: "کل خریداری",
    lastPurchase: "آخری خریداری",
    
    // Expenses
    addExpense: "خرچ شامل کریں",
    expenseType: "خرچ کی قسم",
    amount: "رقم",
    date: "تاریخ",
    rent: "کرایہ",
    utilities: "یوٹیلٹیز",
    salaries: "تنخواہیں",
    supplies: "سپلائیز",
    other: "دیگر",
    
    // Workers
    addWorker: "ورکر شامل کریں",
    workerDetails: "ورکر کی تفصیلات",
    permissions: "اجازتیں",
    role: "کردار",
    admin: "ایڈمن",
    worker: "ورکر",
    
    // Dashboard
    todaySales: "آج کی فروخت",
    weeklySales: "ہفتہ وار فروخت",
    monthlySales: "ماہانہ فروخت",
    totalCustomers: "کل گاہک",
    totalProducts: "کل پروڈکٹس",
    pendingCredits: "زیر التواء ادھار",
    topProducts: "ٹاپ پروڈکٹس",
    topCustomers: "ٹاپ گاہک",
    recentSales: "حالیہ فروخت",
    salesOverview: "فروخت کا جائزہ",
    profitOverview: "منافع کا جائزہ",
    
    // Messages
    savedSuccessfully: "کامیابی سے محفوظ ہو گیا!",
    deletedSuccessfully: "کامیابی سے حذف ہو گیا!",
    errorOccurred: "ایک خرابی پیش آئی",
    confirmDelete: "کیا آپ واقعی حذف کرنا چاہتے ہیں؟",
    noPermission: "آپ کو اس کام کی اجازت نہیں ہے",
    
    // Receipt
    billNo: "بل نمبر",
    invoiceNo: "انوائس نمبر",
    item: "آئٹم",
    qty: "مقدار",
    
    // Time
    today: "آج",
    yesterday: "کل",
    thisWeek: "اس ہفتے",
    thisMonth: "اس مہینے",
    lastMonth: "پچھلے مہینے",
    custom: "مخصوص",
    
    // Actions
    actions: "کارروائیاں",
    moreOptions: "مزید اختیارات",
  },
  ar: {
    // Navigation
    dashboard: "لوحة التحكم",
    newInvoice: "فاتورة جديدة",
    inventory: "المخزون",
    salesHistory: "سجل المبيعات",
    credits: "الائتمان",
    creditManagement: "إدارة الائتمان",
    receivePayment: "استلام الدفع",
    expenses: "المصروفات",
    customers: "العملاء",
    manageWorkers: "إدارة العمال",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    collapse: "طي",
    
    // Common
    save: "حفظ",
    cancel: "إلغاء",
    delete: "حذف",
    edit: "تعديل",
    add: "إضافة",
    search: "بحث",
    filter: "تصفية",
    export: "تصدير",
    import: "استيراد",
    loading: "جاري التحميل...",
    noData: "لا توجد بيانات",
    confirm: "تأكيد",
    back: "رجوع",
    next: "التالي",
    submit: "إرسال",
    reset: "إعادة تعيين",
    close: "إغلاق",
    view: "عرض",
    print: "طباعة",
    download: "تحميل",
    upload: "رفع",
    select: "اختيار",
    all: "الكل",
    none: "لا شيء",
    yes: "نعم",
    no: "لا",
    active: "نشط",
    inactive: "غير نشط",
    pending: "قيد الانتظار",
    completed: "مكتمل",
    
    // Settings
    generalSettings: "الإعدادات العامة",
    receiptSettings: "إعدادات الإيصال",
    languageSettings: "إعدادات اللغة والمنطقة الزمنية",
    profileSettings: "إعدادات الملف الشخصي",
    appName: "اسم التطبيق",
    appDescription: "وصف التطبيق",
    uploadLogo: "رفع الشعار",
    shopName: "اسم المتجر",
    shopAddress: "عنوان المتجر",
    ownerNames: "أسماء المالكين",
    addOwnerName: "إضافة اسم المالك",
    phoneNumbers: "أرقام الهاتف",
    addPhoneNumber: "إضافة رقم هاتف",
    thankYouMessage: "رسالة الشكر",
    footerMessage: "رسالة التذييل",
    workerName: "اسم العامل (على الإيصال)",
    workerPhone: "هاتف العامل (على الإيصال)",
    selectLanguage: "اختر اللغة",
    selectTimezone: "اختر المنطقة الزمنية",
    saveGeneralSettings: "حفظ الإعدادات العامة",
    saveReceiptSettings: "حفظ إعدادات الإيصال",
    saveSettings: "حفظ الإعدادات",
    saveProfile: "حفظ الملف الشخصي",
    
    // Profile
    fullName: "الاسم الكامل",
    email: "البريد الإلكتروني",
    phoneNumber: "رقم الهاتف",
    
    // Invoice
    items: "العناصر",
    total: "المجموع",
    invoiceDate: "تاريخ الفاتورة",
    paymentMethod: "طريقة الدفع",
    cash: "نقدي",
    card: "بطاقة",
    online: "عبر الإنترنت",
    credit: "ائتمان",
    discount: "خصم",
    paidAmount: "المبلغ المدفوع (اختياري)",
    fullPayment: "الدفع الكامل",
    leaveEmptyForFullPayment: "اترك فارغاً للدفع الكامل",
    saveAndPrint: "حفظ وطباعة",
    customerName: "اسم العميل",
    customerPhone: "هاتف العميل",
    selectProduct: "اختر المنتج",
    quantity: "الكمية",
    price: "السعر",
    subtotal: "المجموع الفرعي",
    netTotal: "الصافي",
    totalCost: "التكلفة الإجمالية",
    totalProfit: "الربح الإجمالي",
    finalTotal: "المجموع النهائي",
    paid: "مدفوع",
    due: "مستحق",
    
    // Inventory
    addProduct: "إضافة منتج",
    productName: "اسم المنتج",
    category: "الفئة",
    purchasePrice: "سعر الشراء",
    sellingPrice: "سعر البيع",
    stockQuantity: "كمية المخزون",
    quantityType: "نوع الكمية",
    supplier: "المورد",
    sku: "SKU",
    description: "الوصف",
    lowStock: "مخزون منخفض",
    outOfStock: "نفد المخزون",
    inStock: "متوفر",
    
    // Credits
    addCredit: "إضافة ائتمان",
    creditAmount: "مبلغ الائتمان",
    remainingAmount: "المبلغ المتبقي",
    dueDate: "تاريخ الاستحقاق",
    status: "الحالة",
    notes: "ملاحظات",
    paymentReceived: "تم استلام الدفع",
    markAsPaid: "تحديد كمدفوع",
    
    // Customers
    addCustomer: "إضافة عميل",
    customerDetails: "تفاصيل العميل",
    totalPurchases: "إجمالي المشتريات",
    lastPurchase: "آخر عملية شراء",
    
    // Expenses
    addExpense: "إضافة مصروف",
    expenseType: "نوع المصروف",
    amount: "المبلغ",
    date: "التاريخ",
    rent: "الإيجار",
    utilities: "المرافق",
    salaries: "الرواتب",
    supplies: "اللوازم",
    other: "أخرى",
    
    // Workers
    addWorker: "إضافة عامل",
    workerDetails: "تفاصيل العامل",
    permissions: "الصلاحيات",
    role: "الدور",
    admin: "مدير",
    worker: "عامل",
    
    // Dashboard
    todaySales: "مبيعات اليوم",
    weeklySales: "المبيعات الأسبوعية",
    monthlySales: "المبيعات الشهرية",
    totalCustomers: "إجمالي العملاء",
    totalProducts: "إجمالي المنتجات",
    pendingCredits: "الائتمان المعلق",
    topProducts: "أفضل المنتجات",
    topCustomers: "أفضل العملاء",
    recentSales: "المبيعات الأخيرة",
    salesOverview: "نظرة عامة على المبيعات",
    profitOverview: "نظرة عامة على الأرباح",
    
    // Messages
    savedSuccessfully: "تم الحفظ بنجاح!",
    deletedSuccessfully: "تم الحذف بنجاح!",
    errorOccurred: "حدث خطأ",
    confirmDelete: "هل أنت متأكد أنك تريد الحذف؟",
    noPermission: "ليس لديك صلاحية لهذا الإجراء",
    
    // Receipt
    billNo: "رقم الفاتورة",
    invoiceNo: "رقم الإيصال",
    item: "العنصر",
    qty: "الكمية",
    
    // Time
    today: "اليوم",
    yesterday: "أمس",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    lastMonth: "الشهر الماضي",
    custom: "مخصص",
    
    // Actions
    actions: "الإجراءات",
    moreOptions: "المزيد من الخيارات",
  },
  hi: {
    // Navigation
    dashboard: "डैशबोर्ड",
    newInvoice: "नया इनवॉइस",
    inventory: "इन्वेंटरी",
    salesHistory: "बिक्री इतिहास",
    credits: "उधार",
    creditManagement: "उधार प्रबंधन",
    receivePayment: "भुगतान प्राप्त करें",
    expenses: "खर्च",
    customers: "ग्राहक",
    manageWorkers: "कर्मचारी प्रबंधन",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    collapse: "समेटें",
    
    // Common
    save: "सहेजें",
    cancel: "रद्द करें",
    delete: "हटाएं",
    edit: "संपादित करें",
    add: "जोड़ें",
    search: "खोजें",
    filter: "फ़िल्टर",
    export: "निर्यात",
    import: "आयात",
    loading: "लोड हो रहा है...",
    noData: "कोई डेटा नहीं मिला",
    confirm: "पुष्टि करें",
    back: "वापस",
    next: "अगला",
    submit: "जमा करें",
    reset: "रीसेट",
    close: "बंद करें",
    view: "देखें",
    print: "प्रिंट",
    download: "डाउनलोड",
    upload: "अपलोड",
    select: "चुनें",
    all: "सभी",
    none: "कोई नहीं",
    yes: "हाँ",
    no: "नहीं",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    pending: "लंबित",
    completed: "पूर्ण",
    
    // Settings
    generalSettings: "सामान्य सेटिंग्स",
    receiptSettings: "रसीद सेटिंग्स",
    languageSettings: "भाषा और समय क्षेत्र सेटिंग्स",
    profileSettings: "प्रोफाइल सेटिंग्स",
    appName: "ऐप का नाम",
    appDescription: "ऐप का विवरण",
    uploadLogo: "लोगो अपलोड करें",
    shopName: "दुकान का नाम",
    shopAddress: "दुकान का पता",
    ownerNames: "मालिक के नाम",
    addOwnerName: "मालिक का नाम जोड़ें",
    phoneNumbers: "फोन नंबर",
    addPhoneNumber: "फोन नंबर जोड़ें",
    thankYouMessage: "धन्यवाद संदेश",
    footerMessage: "फुटर संदेश",
    workerName: "कर्मचारी का नाम (रसीद पर)",
    workerPhone: "कर्मचारी का फोन (रसीद पर)",
    selectLanguage: "भाषा चुनें",
    selectTimezone: "समय क्षेत्र चुनें",
    saveGeneralSettings: "सामान्य सेटिंग्स सहेजें",
    saveReceiptSettings: "रसीद सेटिंग्स सहेजें",
    saveSettings: "सेटिंग्स सहेजें",
    saveProfile: "प्रोफाइल सहेजें",
    
    // Profile
    fullName: "पूरा नाम",
    email: "ईमेल",
    phoneNumber: "फोन नंबर",
    
    // Invoice
    items: "आइटम",
    total: "कुल",
    invoiceDate: "इनवॉइस तारीख",
    paymentMethod: "भुगतान विधि",
    cash: "नकद",
    card: "कार्ड",
    online: "ऑनलाइन",
    credit: "उधार",
    discount: "छूट",
    paidAmount: "भुगतान राशि (वैकल्पिक)",
    fullPayment: "पूर्ण भुगतान",
    leaveEmptyForFullPayment: "पूर्ण भुगतान के लिए खाली छोड़ें",
    saveAndPrint: "सहेजें और प्रिंट करें",
    customerName: "ग्राहक का नाम",
    customerPhone: "ग्राहक का फोन",
    selectProduct: "उत्पाद चुनें",
    quantity: "मात्रा",
    price: "कीमत",
    subtotal: "उपयोग",
    netTotal: "शुद्ध कुल",
    totalCost: "कुल लागत",
    totalProfit: "कुल लाभ",
    finalTotal: "अंतिम कुल",
    paid: "भुगतान किया",
    due: "बकाया",
    
    // Inventory
    addProduct: "उत्पाद जोड़ें",
    productName: "उत्पाद का नाम",
    category: "श्रेणी",
    purchasePrice: "खरीद मूल्य",
    sellingPrice: "बिक्री मूल्य",
    stockQuantity: "स्टॉक मात्रा",
    quantityType: "मात्रा प्रकार",
    supplier: "आपूर्तिकर्ता",
    sku: "SKU",
    description: "विवरण",
    lowStock: "कम स्टॉक",
    outOfStock: "स्टॉक खत्म",
    inStock: "स्टॉक में",
    
    // Credits
    addCredit: "उधार जोड़ें",
    creditAmount: "उधार राशि",
    remainingAmount: "शेष राशि",
    dueDate: "अंतिम तिथि",
    status: "स्थिति",
    notes: "नोट्स",
    paymentReceived: "भुगतान प्राप्त",
    markAsPaid: "भुगतान के रूप में चिह्नित करें",
    
    // Customers
    addCustomer: "ग्राहक जोड़ें",
    customerDetails: "ग्राहक विवरण",
    totalPurchases: "कुल खरीदारी",
    lastPurchase: "अंतिम खरीदारी",
    
    // Expenses
    addExpense: "खर्च जोड़ें",
    expenseType: "खर्च का प्रकार",
    amount: "राशि",
    date: "तारीख",
    rent: "किराया",
    utilities: "उपयोगिताएं",
    salaries: "वेतन",
    supplies: "सप्लाई",
    other: "अन्य",
    
    // Workers
    addWorker: "कर्मचारी जोड़ें",
    workerDetails: "कर्मचारी विवरण",
    permissions: "अनुमतियाँ",
    role: "भूमिका",
    admin: "एडमिन",
    worker: "कर्मचारी",
    
    // Dashboard
    todaySales: "आज की बिक्री",
    weeklySales: "साप्ताहिक बिक्री",
    monthlySales: "मासिक बिक्री",
    totalCustomers: "कुल ग्राहक",
    totalProducts: "कुल उत्पाद",
    pendingCredits: "लंबित उधार",
    topProducts: "शीर्ष उत्पाद",
    topCustomers: "शीर्ष ग्राहक",
    recentSales: "हाल की बिक्री",
    salesOverview: "बिक्री अवलोकन",
    profitOverview: "लाभ अवलोकन",
    
    // Messages
    savedSuccessfully: "सफलतापूर्वक सहेजा गया!",
    deletedSuccessfully: "सफलतापूर्वक हटाया गया!",
    errorOccurred: "एक त्रुटि हुई",
    confirmDelete: "क्या आप वाकई हटाना चाहते हैं?",
    noPermission: "आपको इस कार्य की अनुमति नहीं है",
    
    // Receipt
    billNo: "बिल नंबर",
    invoiceNo: "इनवॉइस नंबर",
    item: "आइटम",
    qty: "मात्रा",
    
    // Time
    today: "आज",
    yesterday: "कल",
    thisWeek: "इस सप्ताह",
    thisMonth: "इस महीने",
    lastMonth: "पिछले महीने",
    custom: "कस्टम",
    
    // Actions
    actions: "क्रियाएं",
    moreOptions: "अधिक विकल्प",
  },
  // Spanish
  es: {
    dashboard: "Panel", newInvoice: "Nueva Factura", inventory: "Inventario", salesHistory: "Historial de Ventas",
    credits: "Créditos", creditManagement: "Gestión de Créditos", receivePayment: "Recibir Pago", expenses: "Gastos",
    customers: "Clientes", manageWorkers: "Gestionar Trabajadores", settings: "Configuración", logout: "Cerrar Sesión",
    collapse: "Colapsar", save: "Guardar", cancel: "Cancelar", delete: "Eliminar", edit: "Editar", add: "Agregar",
    search: "Buscar", filter: "Filtrar", export: "Exportar", import: "Importar", loading: "Cargando...",
    noData: "No hay datos", confirm: "Confirmar", back: "Atrás", next: "Siguiente", submit: "Enviar",
    reset: "Restablecer", close: "Cerrar", view: "Ver", print: "Imprimir", download: "Descargar", upload: "Subir",
    select: "Seleccionar", all: "Todo", none: "Ninguno", yes: "Sí", no: "No", active: "Activo", inactive: "Inactivo",
    pending: "Pendiente", completed: "Completado", generalSettings: "Configuración General", receiptSettings: "Configuración de Recibo",
    languageSettings: "Configuración de Idioma", profileSettings: "Configuración de Perfil", appName: "Nombre de App",
    appDescription: "Descripción de App", uploadLogo: "Subir Logo", shopName: "Nombre de Tienda", shopAddress: "Dirección",
    ownerNames: "Nombres de Propietarios", addOwnerName: "Agregar Propietario", phoneNumbers: "Números de Teléfono",
    addPhoneNumber: "Agregar Teléfono", thankYouMessage: "Mensaje de Gracias", footerMessage: "Mensaje de Pie",
    workerName: "Nombre del Trabajador", workerPhone: "Teléfono del Trabajador", selectLanguage: "Seleccionar Idioma",
    selectTimezone: "Seleccionar Zona Horaria", saveGeneralSettings: "Guardar Configuración General",
    saveReceiptSettings: "Guardar Configuración de Recibo", saveSettings: "Guardar Configuración", saveProfile: "Guardar Perfil",
    fullName: "Nombre Completo", email: "Correo", phoneNumber: "Teléfono", items: "Artículos", total: "Total",
    invoiceDate: "Fecha de Factura", paymentMethod: "Método de Pago", cash: "Efectivo", card: "Tarjeta", online: "En línea",
    credit: "Crédito", discount: "Descuento", paidAmount: "Monto Pagado", fullPayment: "Pago Completo",
    leaveEmptyForFullPayment: "Dejar vacío para pago completo", saveAndPrint: "Guardar e Imprimir",
    customerName: "Nombre del Cliente", customerPhone: "Teléfono del Cliente", selectProduct: "Seleccionar Producto",
    quantity: "Cantidad", price: "Precio", subtotal: "Subtotal", netTotal: "Total Neto", totalCost: "Costo Total",
    totalProfit: "Ganancia Total", finalTotal: "Total Final", paid: "Pagado", due: "Pendiente", addProduct: "Agregar Producto",
    productName: "Nombre del Producto", category: "Categoría", purchasePrice: "Precio de Compra", sellingPrice: "Precio de Venta",
    stockQuantity: "Cantidad en Stock", quantityType: "Tipo de Cantidad", supplier: "Proveedor", sku: "SKU",
    description: "Descripción", lowStock: "Stock Bajo", outOfStock: "Sin Stock", inStock: "En Stock", addCredit: "Agregar Crédito",
    creditAmount: "Monto de Crédito", remainingAmount: "Monto Restante", dueDate: "Fecha de Vencimiento", status: "Estado",
    notes: "Notas", paymentReceived: "Pago Recibido", markAsPaid: "Marcar como Pagado", addCustomer: "Agregar Cliente",
    customerDetails: "Detalles del Cliente", totalPurchases: "Compras Totales", lastPurchase: "Última Compra",
    addExpense: "Agregar Gasto", expenseType: "Tipo de Gasto", amount: "Monto", date: "Fecha", rent: "Alquiler",
    utilities: "Servicios", salaries: "Salarios", supplies: "Suministros", other: "Otro", addWorker: "Agregar Trabajador",
    workerDetails: "Detalles del Trabajador", permissions: "Permisos", role: "Rol", admin: "Admin", worker: "Trabajador",
    todaySales: "Ventas de Hoy", weeklySales: "Ventas Semanales", monthlySales: "Ventas Mensuales",
    totalCustomers: "Total de Clientes", totalProducts: "Total de Productos", pendingCredits: "Créditos Pendientes",
    topProducts: "Productos Top", topCustomers: "Clientes Top", recentSales: "Ventas Recientes",
    salesOverview: "Resumen de Ventas", profitOverview: "Resumen de Ganancias", savedSuccessfully: "¡Guardado exitosamente!",
    deletedSuccessfully: "¡Eliminado exitosamente!", errorOccurred: "Ocurrió un error", confirmDelete: "¿Confirmar eliminación?",
    noPermission: "Sin permiso", billNo: "Número de Factura", invoiceNo: "Número de Recibo", item: "Artículo", qty: "Cant.",
    today: "Hoy", yesterday: "Ayer", thisWeek: "Esta Semana", thisMonth: "Este Mes", lastMonth: "Mes Pasado",
    custom: "Personalizado", actions: "Acciones", moreOptions: "Más Opciones",
  },
  // French
  fr: {
    dashboard: "Tableau de bord", newInvoice: "Nouvelle Facture", inventory: "Inventaire", salesHistory: "Historique des Ventes",
    credits: "Crédits", creditManagement: "Gestion des Crédits", receivePayment: "Recevoir Paiement", expenses: "Dépenses",
    customers: "Clients", manageWorkers: "Gérer les Employés", settings: "Paramètres", logout: "Déconnexion",
    collapse: "Réduire", save: "Enregistrer", cancel: "Annuler", delete: "Supprimer", edit: "Modifier", add: "Ajouter",
    search: "Rechercher", filter: "Filtrer", export: "Exporter", import: "Importer", loading: "Chargement...",
    noData: "Aucune donnée", confirm: "Confirmer", back: "Retour", next: "Suivant", submit: "Soumettre",
    reset: "Réinitialiser", close: "Fermer", view: "Voir", print: "Imprimer", download: "Télécharger", upload: "Téléverser",
    select: "Sélectionner", all: "Tout", none: "Aucun", yes: "Oui", no: "Non", active: "Actif", inactive: "Inactif",
    pending: "En attente", completed: "Terminé", generalSettings: "Paramètres Généraux", receiptSettings: "Paramètres de Reçu",
    languageSettings: "Paramètres de Langue", profileSettings: "Paramètres de Profil", appName: "Nom de l'Application",
    appDescription: "Description", uploadLogo: "Téléverser Logo", shopName: "Nom du Magasin", shopAddress: "Adresse",
    ownerNames: "Noms des Propriétaires", addOwnerName: "Ajouter Propriétaire", phoneNumbers: "Numéros de Téléphone",
    addPhoneNumber: "Ajouter Téléphone", thankYouMessage: "Message de Remerciement", footerMessage: "Message de Pied",
    workerName: "Nom de l'Employé", workerPhone: "Téléphone de l'Employé", selectLanguage: "Sélectionner Langue",
    selectTimezone: "Sélectionner Fuseau Horaire", saveGeneralSettings: "Enregistrer Paramètres Généraux",
    saveReceiptSettings: "Enregistrer Paramètres de Reçu", saveSettings: "Enregistrer Paramètres", saveProfile: "Enregistrer Profil",
    fullName: "Nom Complet", email: "Email", phoneNumber: "Téléphone", items: "Articles", total: "Total",
    invoiceDate: "Date de Facture", paymentMethod: "Mode de Paiement", cash: "Espèces", card: "Carte", online: "En ligne",
    credit: "Crédit", discount: "Réduction", paidAmount: "Montant Payé", fullPayment: "Paiement Complet",
    leaveEmptyForFullPayment: "Laisser vide pour paiement complet", saveAndPrint: "Enregistrer et Imprimer",
    customerName: "Nom du Client", customerPhone: "Téléphone du Client", selectProduct: "Sélectionner Produit",
    quantity: "Quantité", price: "Prix", subtotal: "Sous-total", netTotal: "Total Net", totalCost: "Coût Total",
    totalProfit: "Profit Total", finalTotal: "Total Final", paid: "Payé", due: "Dû", addProduct: "Ajouter Produit",
    productName: "Nom du Produit", category: "Catégorie", purchasePrice: "Prix d'Achat", sellingPrice: "Prix de Vente",
    stockQuantity: "Quantité en Stock", quantityType: "Type de Quantité", supplier: "Fournisseur", sku: "SKU",
    description: "Description", lowStock: "Stock Faible", outOfStock: "Rupture de Stock", inStock: "En Stock", addCredit: "Ajouter Crédit",
    creditAmount: "Montant du Crédit", remainingAmount: "Montant Restant", dueDate: "Date d'Échéance", status: "Statut",
    notes: "Notes", paymentReceived: "Paiement Reçu", markAsPaid: "Marquer comme Payé", addCustomer: "Ajouter Client",
    customerDetails: "Détails du Client", totalPurchases: "Achats Totaux", lastPurchase: "Dernier Achat",
    addExpense: "Ajouter Dépense", expenseType: "Type de Dépense", amount: "Montant", date: "Date", rent: "Loyer",
    utilities: "Services", salaries: "Salaires", supplies: "Fournitures", other: "Autre", addWorker: "Ajouter Employé",
    workerDetails: "Détails de l'Employé", permissions: "Permissions", role: "Rôle", admin: "Admin", worker: "Employé",
    todaySales: "Ventes du Jour", weeklySales: "Ventes Hebdomadaires", monthlySales: "Ventes Mensuelles",
    totalCustomers: "Total Clients", totalProducts: "Total Produits", pendingCredits: "Crédits en Attente",
    topProducts: "Meilleurs Produits", topCustomers: "Meilleurs Clients", recentSales: "Ventes Récentes",
    salesOverview: "Aperçu des Ventes", profitOverview: "Aperçu des Profits", savedSuccessfully: "Enregistré avec succès!",
    deletedSuccessfully: "Supprimé avec succès!", errorOccurred: "Une erreur s'est produite", confirmDelete: "Confirmer la suppression?",
    noPermission: "Pas de permission", billNo: "Numéro de Facture", invoiceNo: "Numéro de Reçu", item: "Article", qty: "Qté",
    today: "Aujourd'hui", yesterday: "Hier", thisWeek: "Cette Semaine", thisMonth: "Ce Mois", lastMonth: "Mois Dernier",
    custom: "Personnalisé", actions: "Actions", moreOptions: "Plus d'Options",
  },
  // German
  de: {
    dashboard: "Dashboard", newInvoice: "Neue Rechnung", inventory: "Inventar", salesHistory: "Verkaufshistorie",
    credits: "Kredite", creditManagement: "Kreditverwaltung", receivePayment: "Zahlung erhalten", expenses: "Ausgaben",
    customers: "Kunden", manageWorkers: "Mitarbeiter verwalten", settings: "Einstellungen", logout: "Abmelden",
    collapse: "Einklappen", save: "Speichern", cancel: "Abbrechen", delete: "Löschen", edit: "Bearbeiten", add: "Hinzufügen",
    search: "Suchen", filter: "Filtern", export: "Exportieren", import: "Importieren", loading: "Wird geladen...",
    noData: "Keine Daten", confirm: "Bestätigen", back: "Zurück", next: "Weiter", submit: "Absenden",
    reset: "Zurücksetzen", close: "Schließen", view: "Ansehen", print: "Drucken", download: "Herunterladen", upload: "Hochladen",
    select: "Auswählen", all: "Alle", none: "Keine", yes: "Ja", no: "Nein", active: "Aktiv", inactive: "Inaktiv",
    pending: "Ausstehend", completed: "Abgeschlossen", generalSettings: "Allgemeine Einstellungen", receiptSettings: "Quittungseinstellungen",
    languageSettings: "Spracheinstellungen", profileSettings: "Profileinstellungen", appName: "App-Name",
    appDescription: "Beschreibung", uploadLogo: "Logo hochladen", shopName: "Geschäftsname", shopAddress: "Adresse",
    ownerNames: "Inhabernamen", addOwnerName: "Inhaber hinzufügen", phoneNumbers: "Telefonnummern",
    addPhoneNumber: "Telefon hinzufügen", thankYouMessage: "Dankenachricht", footerMessage: "Fußzeilennachricht",
    workerName: "Mitarbeitername", workerPhone: "Mitarbeitertelefon", selectLanguage: "Sprache auswählen",
    selectTimezone: "Zeitzone auswählen", saveGeneralSettings: "Allgemeine Einstellungen speichern",
    saveReceiptSettings: "Quittungseinstellungen speichern", saveSettings: "Einstellungen speichern", saveProfile: "Profil speichern",
    fullName: "Vollständiger Name", email: "E-Mail", phoneNumber: "Telefon", items: "Artikel", total: "Gesamt",
    invoiceDate: "Rechnungsdatum", paymentMethod: "Zahlungsmethode", cash: "Bar", card: "Karte", online: "Online",
    credit: "Kredit", discount: "Rabatt", paidAmount: "Bezahlter Betrag", fullPayment: "Vollzahlung",
    leaveEmptyForFullPayment: "Leer lassen für Vollzahlung", saveAndPrint: "Speichern und Drucken",
    customerName: "Kundenname", customerPhone: "Kundentelefon", selectProduct: "Produkt auswählen",
    quantity: "Menge", price: "Preis", subtotal: "Zwischensumme", netTotal: "Nettosumme", totalCost: "Gesamtkosten",
    totalProfit: "Gesamtgewinn", finalTotal: "Endsumme", paid: "Bezahlt", due: "Fällig", addProduct: "Produkt hinzufügen",
    productName: "Produktname", category: "Kategorie", purchasePrice: "Einkaufspreis", sellingPrice: "Verkaufspreis",
    stockQuantity: "Lagerbestand", quantityType: "Mengentyp", supplier: "Lieferant", sku: "SKU",
    description: "Beschreibung", lowStock: "Niedriger Bestand", outOfStock: "Nicht auf Lager", inStock: "Auf Lager", addCredit: "Kredit hinzufügen",
    creditAmount: "Kreditbetrag", remainingAmount: "Restbetrag", dueDate: "Fälligkeitsdatum", status: "Status",
    notes: "Notizen", paymentReceived: "Zahlung erhalten", markAsPaid: "Als bezahlt markieren", addCustomer: "Kunde hinzufügen",
    customerDetails: "Kundendetails", totalPurchases: "Gesamtkäufe", lastPurchase: "Letzter Kauf",
    addExpense: "Ausgabe hinzufügen", expenseType: "Ausgabentyp", amount: "Betrag", date: "Datum", rent: "Miete",
    utilities: "Nebenkosten", salaries: "Gehälter", supplies: "Zubehör", other: "Andere", addWorker: "Mitarbeiter hinzufügen",
    workerDetails: "Mitarbeiterdetails", permissions: "Berechtigungen", role: "Rolle", admin: "Admin", worker: "Mitarbeiter",
    todaySales: "Heutige Verkäufe", weeklySales: "Wöchentliche Verkäufe", monthlySales: "Monatliche Verkäufe",
    totalCustomers: "Gesamtkunden", totalProducts: "Gesamtprodukte", pendingCredits: "Ausstehende Kredite",
    topProducts: "Top-Produkte", topCustomers: "Top-Kunden", recentSales: "Aktuelle Verkäufe",
    salesOverview: "Verkaufsübersicht", profitOverview: "Gewinnübersicht", savedSuccessfully: "Erfolgreich gespeichert!",
    deletedSuccessfully: "Erfolgreich gelöscht!", errorOccurred: "Ein Fehler ist aufgetreten", confirmDelete: "Löschen bestätigen?",
    noPermission: "Keine Berechtigung", billNo: "Rechnungsnummer", invoiceNo: "Quittungsnummer", item: "Artikel", qty: "Menge",
    today: "Heute", yesterday: "Gestern", thisWeek: "Diese Woche", thisMonth: "Dieser Monat", lastMonth: "Letzter Monat",
    custom: "Benutzerdefiniert", actions: "Aktionen", moreOptions: "Mehr Optionen",
  },
  // Chinese
  zh: {
    dashboard: "仪表板", newInvoice: "新发票", inventory: "库存", salesHistory: "销售历史",
    credits: "信用", creditManagement: "信用管理", receivePayment: "收款", expenses: "支出",
    customers: "客户", manageWorkers: "管理员工", settings: "设置", logout: "登出",
    collapse: "折叠", save: "保存", cancel: "取消", delete: "删除", edit: "编辑", add: "添加",
    search: "搜索", filter: "筛选", export: "导出", import: "导入", loading: "加载中...",
    noData: "无数据", confirm: "确认", back: "返回", next: "下一步", submit: "提交",
    reset: "重置", close: "关闭", view: "查看", print: "打印", download: "下载", upload: "上传",
    select: "选择", all: "全部", none: "无", yes: "是", no: "否", active: "活跃", inactive: "非活跃",
    pending: "待处理", completed: "已完成", generalSettings: "常规设置", receiptSettings: "收据设置",
    languageSettings: "语言设置", profileSettings: "个人设置", appName: "应用名称",
    appDescription: "描述", uploadLogo: "上传标志", shopName: "店铺名称", shopAddress: "地址",
    ownerNames: "所有者名称", addOwnerName: "添加所有者", phoneNumbers: "电话号码",
    addPhoneNumber: "添加电话", thankYouMessage: "感谢信息", footerMessage: "页脚信息",
    workerName: "员工姓名", workerPhone: "员工电话", selectLanguage: "选择语言",
    selectTimezone: "选择时区", saveGeneralSettings: "保存常规设置",
    saveReceiptSettings: "保存收据设置", saveSettings: "保存设置", saveProfile: "保存个人资料",
    fullName: "全名", email: "电子邮件", phoneNumber: "电话", items: "商品", total: "总计",
    invoiceDate: "发票日期", paymentMethod: "支付方式", cash: "现金", card: "卡", online: "在线",
    credit: "信用", discount: "折扣", paidAmount: "已付金额", fullPayment: "全额付款",
    leaveEmptyForFullPayment: "留空表示全额付款", saveAndPrint: "保存并打印",
    customerName: "客户姓名", customerPhone: "客户电话", selectProduct: "选择产品",
    quantity: "数量", price: "价格", subtotal: "小计", netTotal: "净总额", totalCost: "总成本",
    totalProfit: "总利润", finalTotal: "最终总额", paid: "已付", due: "应付", addProduct: "添加产品",
    productName: "产品名称", category: "类别", purchasePrice: "采购价格", sellingPrice: "销售价格",
    stockQuantity: "库存数量", quantityType: "数量类型", supplier: "供应商", sku: "SKU",
    description: "描述", lowStock: "库存不足", outOfStock: "缺货", inStock: "有货", addCredit: "添加信用",
    creditAmount: "信用金额", remainingAmount: "剩余金额", dueDate: "到期日", status: "状态",
    notes: "备注", paymentReceived: "已收款", markAsPaid: "标记为已付", addCustomer: "添加客户",
    customerDetails: "客户详情", totalPurchases: "总购买", lastPurchase: "上次购买",
    addExpense: "添加支出", expenseType: "支出类型", amount: "金额", date: "日期", rent: "租金",
    utilities: "公用事业", salaries: "工资", supplies: "用品", other: "其他", addWorker: "添加员工",
    workerDetails: "员工详情", permissions: "权限", role: "角色", admin: "管理员", worker: "员工",
    todaySales: "今日销售", weeklySales: "每周销售", monthlySales: "每月销售",
    totalCustomers: "总客户", totalProducts: "总产品", pendingCredits: "待处理信用",
    topProducts: "热门产品", topCustomers: "热门客户", recentSales: "最近销售",
    salesOverview: "销售概览", profitOverview: "利润概览", savedSuccessfully: "保存成功！",
    deletedSuccessfully: "删除成功！", errorOccurred: "发生错误", confirmDelete: "确认删除？",
    noPermission: "无权限", billNo: "账单号", invoiceNo: "发票号", item: "商品", qty: "数量",
    today: "今天", yesterday: "昨天", thisWeek: "本周", thisMonth: "本月", lastMonth: "上月",
    custom: "自定义", actions: "操作", moreOptions: "更多选项",
  },
  // Portuguese
  pt: {
    dashboard: "Painel", newInvoice: "Nova Fatura", inventory: "Inventário", salesHistory: "Histórico de Vendas",
    credits: "Créditos", creditManagement: "Gestão de Créditos", receivePayment: "Receber Pagamento", expenses: "Despesas",
    customers: "Clientes", manageWorkers: "Gerir Funcionários", settings: "Configurações", logout: "Sair",
    collapse: "Recolher", save: "Guardar", cancel: "Cancelar", delete: "Eliminar", edit: "Editar", add: "Adicionar",
    search: "Pesquisar", filter: "Filtrar", export: "Exportar", import: "Importar", loading: "A carregar...",
    noData: "Sem dados", confirm: "Confirmar", back: "Voltar", next: "Seguinte", submit: "Submeter",
    reset: "Reiniciar", close: "Fechar", view: "Ver", print: "Imprimir", download: "Descarregar", upload: "Carregar",
    select: "Selecionar", all: "Tudo", none: "Nenhum", yes: "Sim", no: "Não", active: "Ativo", inactive: "Inativo",
    pending: "Pendente", completed: "Concluído", generalSettings: "Configurações Gerais", receiptSettings: "Configurações de Recibo",
    languageSettings: "Configurações de Idioma", profileSettings: "Configurações de Perfil", appName: "Nome da App",
    appDescription: "Descrição", uploadLogo: "Carregar Logo", shopName: "Nome da Loja", shopAddress: "Morada",
    ownerNames: "Nomes dos Proprietários", addOwnerName: "Adicionar Proprietário", phoneNumbers: "Números de Telefone",
    addPhoneNumber: "Adicionar Telefone", thankYouMessage: "Mensagem de Agradecimento", footerMessage: "Mensagem de Rodapé",
    workerName: "Nome do Funcionário", workerPhone: "Telefone do Funcionário", selectLanguage: "Selecionar Idioma",
    selectTimezone: "Selecionar Fuso Horário", saveGeneralSettings: "Guardar Configurações Gerais",
    saveReceiptSettings: "Guardar Configurações de Recibo", saveSettings: "Guardar Configurações", saveProfile: "Guardar Perfil",
    fullName: "Nome Completo", email: "Email", phoneNumber: "Telefone", items: "Itens", total: "Total",
    invoiceDate: "Data da Fatura", paymentMethod: "Método de Pagamento", cash: "Dinheiro", card: "Cartão", online: "Online",
    credit: "Crédito", discount: "Desconto", paidAmount: "Valor Pago", fullPayment: "Pagamento Completo",
    leaveEmptyForFullPayment: "Deixar vazio para pagamento completo", saveAndPrint: "Guardar e Imprimir",
    customerName: "Nome do Cliente", customerPhone: "Telefone do Cliente", selectProduct: "Selecionar Produto",
    quantity: "Quantidade", price: "Preço", subtotal: "Subtotal", netTotal: "Total Líquido", totalCost: "Custo Total",
    totalProfit: "Lucro Total", finalTotal: "Total Final", paid: "Pago", due: "A pagar", addProduct: "Adicionar Produto",
    productName: "Nome do Produto", category: "Categoria", purchasePrice: "Preço de Compra", sellingPrice: "Preço de Venda",
    stockQuantity: "Quantidade em Stock", quantityType: "Tipo de Quantidade", supplier: "Fornecedor", sku: "SKU",
    description: "Descrição", lowStock: "Stock Baixo", outOfStock: "Sem Stock", inStock: "Em Stock", addCredit: "Adicionar Crédito",
    creditAmount: "Valor do Crédito", remainingAmount: "Valor Restante", dueDate: "Data de Vencimento", status: "Estado",
    notes: "Notas", paymentReceived: "Pagamento Recebido", markAsPaid: "Marcar como Pago", addCustomer: "Adicionar Cliente",
    customerDetails: "Detalhes do Cliente", totalPurchases: "Total de Compras", lastPurchase: "Última Compra",
    addExpense: "Adicionar Despesa", expenseType: "Tipo de Despesa", amount: "Valor", date: "Data", rent: "Renda",
    utilities: "Serviços", salaries: "Salários", supplies: "Fornecimentos", other: "Outro", addWorker: "Adicionar Funcionário",
    workerDetails: "Detalhes do Funcionário", permissions: "Permissões", role: "Função", admin: "Admin", worker: "Funcionário",
    todaySales: "Vendas de Hoje", weeklySales: "Vendas Semanais", monthlySales: "Vendas Mensais",
    totalCustomers: "Total de Clientes", totalProducts: "Total de Produtos", pendingCredits: "Créditos Pendentes",
    topProducts: "Produtos Top", topCustomers: "Clientes Top", recentSales: "Vendas Recentes",
    salesOverview: "Resumo de Vendas", profitOverview: "Resumo de Lucros", savedSuccessfully: "Guardado com sucesso!",
    deletedSuccessfully: "Eliminado com sucesso!", errorOccurred: "Ocorreu um erro", confirmDelete: "Confirmar eliminação?",
    noPermission: "Sem permissão", billNo: "Número da Fatura", invoiceNo: "Número do Recibo", item: "Item", qty: "Qtd",
    today: "Hoje", yesterday: "Ontem", thisWeek: "Esta Semana", thisMonth: "Este Mês", lastMonth: "Mês Passado",
    custom: "Personalizado", actions: "Ações", moreOptions: "Mais Opções",
  },
  // Turkish
  tr: {
    dashboard: "Gösterge Paneli", newInvoice: "Yeni Fatura", inventory: "Envanter", salesHistory: "Satış Geçmişi",
    credits: "Krediler", creditManagement: "Kredi Yönetimi", receivePayment: "Ödeme Al", expenses: "Giderler",
    customers: "Müşteriler", manageWorkers: "Çalışanları Yönet", settings: "Ayarlar", logout: "Çıkış",
    collapse: "Daralt", save: "Kaydet", cancel: "İptal", delete: "Sil", edit: "Düzenle", add: "Ekle",
    search: "Ara", filter: "Filtrele", export: "Dışa Aktar", import: "İçe Aktar", loading: "Yükleniyor...",
    noData: "Veri yok", confirm: "Onayla", back: "Geri", next: "İleri", submit: "Gönder",
    reset: "Sıfırla", close: "Kapat", view: "Görüntüle", print: "Yazdır", download: "İndir", upload: "Yükle",
    select: "Seç", all: "Tümü", none: "Hiçbiri", yes: "Evet", no: "Hayır", active: "Aktif", inactive: "Pasif",
    pending: "Beklemede", completed: "Tamamlandı", generalSettings: "Genel Ayarlar", receiptSettings: "Makbuz Ayarları",
    languageSettings: "Dil Ayarları", profileSettings: "Profil Ayarları", appName: "Uygulama Adı",
    appDescription: "Açıklama", uploadLogo: "Logo Yükle", shopName: "Mağaza Adı", shopAddress: "Adres",
    ownerNames: "Sahip Adları", addOwnerName: "Sahip Ekle", phoneNumbers: "Telefon Numaraları",
    addPhoneNumber: "Telefon Ekle", thankYouMessage: "Teşekkür Mesajı", footerMessage: "Alt Bilgi Mesajı",
    workerName: "Çalışan Adı", workerPhone: "Çalışan Telefonu", selectLanguage: "Dil Seç",
    selectTimezone: "Saat Dilimi Seç", saveGeneralSettings: "Genel Ayarları Kaydet",
    saveReceiptSettings: "Makbuz Ayarlarını Kaydet", saveSettings: "Ayarları Kaydet", saveProfile: "Profili Kaydet",
    fullName: "Tam Ad", email: "E-posta", phoneNumber: "Telefon", items: "Ürünler", total: "Toplam",
    invoiceDate: "Fatura Tarihi", paymentMethod: "Ödeme Yöntemi", cash: "Nakit", card: "Kart", online: "Çevrimiçi",
    credit: "Kredi", discount: "İndirim", paidAmount: "Ödenen Tutar", fullPayment: "Tam Ödeme",
    leaveEmptyForFullPayment: "Tam ödeme için boş bırakın", saveAndPrint: "Kaydet ve Yazdır",
    customerName: "Müşteri Adı", customerPhone: "Müşteri Telefonu", selectProduct: "Ürün Seç",
    quantity: "Miktar", price: "Fiyat", subtotal: "Ara Toplam", netTotal: "Net Toplam", totalCost: "Toplam Maliyet",
    totalProfit: "Toplam Kar", finalTotal: "Son Toplam", paid: "Ödendi", due: "Borç", addProduct: "Ürün Ekle",
    productName: "Ürün Adı", category: "Kategori", purchasePrice: "Alış Fiyatı", sellingPrice: "Satış Fiyatı",
    stockQuantity: "Stok Miktarı", quantityType: "Miktar Türü", supplier: "Tedarikçi", sku: "SKU",
    description: "Açıklama", lowStock: "Düşük Stok", outOfStock: "Stokta Yok", inStock: "Stokta", addCredit: "Kredi Ekle",
    creditAmount: "Kredi Tutarı", remainingAmount: "Kalan Tutar", dueDate: "Vade Tarihi", status: "Durum",
    notes: "Notlar", paymentReceived: "Ödeme Alındı", markAsPaid: "Ödendi Olarak İşaretle", addCustomer: "Müşteri Ekle",
    customerDetails: "Müşteri Detayları", totalPurchases: "Toplam Alışveriş", lastPurchase: "Son Alışveriş",
    addExpense: "Gider Ekle", expenseType: "Gider Türü", amount: "Tutar", date: "Tarih", rent: "Kira",
    utilities: "Faturalar", salaries: "Maaşlar", supplies: "Malzemeler", other: "Diğer", addWorker: "Çalışan Ekle",
    workerDetails: "Çalışan Detayları", permissions: "İzinler", role: "Rol", admin: "Yönetici", worker: "Çalışan",
    todaySales: "Bugünün Satışları", weeklySales: "Haftalık Satışlar", monthlySales: "Aylık Satışlar",
    totalCustomers: "Toplam Müşteri", totalProducts: "Toplam Ürün", pendingCredits: "Bekleyen Krediler",
    topProducts: "En İyi Ürünler", topCustomers: "En İyi Müşteriler", recentSales: "Son Satışlar",
    salesOverview: "Satış Özeti", profitOverview: "Kar Özeti", savedSuccessfully: "Başarıyla kaydedildi!",
    deletedSuccessfully: "Başarıyla silindi!", errorOccurred: "Bir hata oluştu", confirmDelete: "Silme onayı?",
    noPermission: "İzin yok", billNo: "Fatura No", invoiceNo: "Makbuz No", item: "Ürün", qty: "Adet",
    today: "Bugün", yesterday: "Dün", thisWeek: "Bu Hafta", thisMonth: "Bu Ay", lastMonth: "Geçen Ay",
    custom: "Özel", actions: "İşlemler", moreOptions: "Daha Fazla Seçenek",
  },
  // Russian
  ru: {
    dashboard: "Панель", newInvoice: "Новый счёт", inventory: "Инвентарь", salesHistory: "История продаж",
    credits: "Кредиты", creditManagement: "Управление кредитами", receivePayment: "Получить оплату", expenses: "Расходы",
    customers: "Клиенты", manageWorkers: "Управление сотрудниками", settings: "Настройки", logout: "Выйти",
    collapse: "Свернуть", save: "Сохранить", cancel: "Отмена", delete: "Удалить", edit: "Редактировать", add: "Добавить",
    search: "Поиск", filter: "Фильтр", export: "Экспорт", import: "Импорт", loading: "Загрузка...",
    noData: "Нет данных", confirm: "Подтвердить", back: "Назад", next: "Далее", submit: "Отправить",
    reset: "Сбросить", close: "Закрыть", view: "Просмотр", print: "Печать", download: "Скачать", upload: "Загрузить",
    select: "Выбрать", all: "Все", none: "Нет", yes: "Да", no: "Нет", active: "Активный", inactive: "Неактивный",
    pending: "Ожидание", completed: "Завершено", generalSettings: "Общие настройки", receiptSettings: "Настройки чека",
    languageSettings: "Настройки языка", profileSettings: "Настройки профиля", appName: "Название приложения",
    appDescription: "Описание", uploadLogo: "Загрузить логотип", shopName: "Название магазина", shopAddress: "Адрес",
    ownerNames: "Имена владельцев", addOwnerName: "Добавить владельца", phoneNumbers: "Номера телефонов",
    addPhoneNumber: "Добавить телефон", thankYouMessage: "Благодарственное сообщение", footerMessage: "Сообщение в нижнем колонтитуле",
    workerName: "Имя сотрудника", workerPhone: "Телефон сотрудника", selectLanguage: "Выбрать язык",
    selectTimezone: "Выбрать часовой пояс", saveGeneralSettings: "Сохранить общие настройки",
    saveReceiptSettings: "Сохранить настройки чека", saveSettings: "Сохранить настройки", saveProfile: "Сохранить профиль",
    fullName: "Полное имя", email: "Эл. почта", phoneNumber: "Телефон", items: "Товары", total: "Итого",
    invoiceDate: "Дата счёта", paymentMethod: "Способ оплаты", cash: "Наличные", card: "Карта", online: "Онлайн",
    credit: "Кредит", discount: "Скидка", paidAmount: "Оплаченная сумма", fullPayment: "Полная оплата",
    leaveEmptyForFullPayment: "Оставьте пустым для полной оплаты", saveAndPrint: "Сохранить и распечатать",
    customerName: "Имя клиента", customerPhone: "Телефон клиента", selectProduct: "Выбрать товар",
    quantity: "Количество", price: "Цена", subtotal: "Подытог", netTotal: "Чистый итог", totalCost: "Общая стоимость",
    totalProfit: "Общая прибыль", finalTotal: "Итоговая сумма", paid: "Оплачено", due: "К оплате", addProduct: "Добавить товар",
    productName: "Название товара", category: "Категория", purchasePrice: "Цена закупки", sellingPrice: "Цена продажи",
    stockQuantity: "Количество на складе", quantityType: "Тип количества", supplier: "Поставщик", sku: "Артикул",
    description: "Описание", lowStock: "Мало на складе", outOfStock: "Нет в наличии", inStock: "В наличии", addCredit: "Добавить кредит",
    creditAmount: "Сумма кредита", remainingAmount: "Остаток", dueDate: "Срок", status: "Статус",
    notes: "Заметки", paymentReceived: "Оплата получена", markAsPaid: "Отметить как оплачено", addCustomer: "Добавить клиента",
    customerDetails: "Данные клиента", totalPurchases: "Всего покупок", lastPurchase: "Последняя покупка",
    addExpense: "Добавить расход", expenseType: "Тип расхода", amount: "Сумма", date: "Дата", rent: "Аренда",
    utilities: "Коммунальные услуги", salaries: "Зарплаты", supplies: "Снабжение", other: "Другое", addWorker: "Добавить сотрудника",
    workerDetails: "Данные сотрудника", permissions: "Разрешения", role: "Роль", admin: "Админ", worker: "Сотрудник",
    todaySales: "Продажи сегодня", weeklySales: "Продажи за неделю", monthlySales: "Продажи за месяц",
    totalCustomers: "Всего клиентов", totalProducts: "Всего товаров", pendingCredits: "Ожидающие кредиты",
    topProducts: "Лучшие товары", topCustomers: "Лучшие клиенты", recentSales: "Последние продажи",
    salesOverview: "Обзор продаж", profitOverview: "Обзор прибыли", savedSuccessfully: "Успешно сохранено!",
    deletedSuccessfully: "Успешно удалено!", errorOccurred: "Произошла ошибка", confirmDelete: "Подтвердить удаление?",
    noPermission: "Нет разрешения", billNo: "Номер счёта", invoiceNo: "Номер чека", item: "Товар", qty: "Кол-во",
    today: "Сегодня", yesterday: "Вчера", thisWeek: "Эта неделя", thisMonth: "Этот месяц", lastMonth: "Прошлый месяц",
    custom: "Пользовательский", actions: "Действия", moreOptions: "Больше опций",
  },
  // Japanese
  ja: {
    dashboard: "ダッシュボード", newInvoice: "新規請求書", inventory: "在庫", salesHistory: "販売履歴",
    credits: "クレジット", creditManagement: "クレジット管理", receivePayment: "支払い受領", expenses: "経費",
    customers: "顧客", manageWorkers: "従業員管理", settings: "設定", logout: "ログアウト",
    collapse: "折りたたむ", save: "保存", cancel: "キャンセル", delete: "削除", edit: "編集", add: "追加",
    search: "検索", filter: "フィルター", export: "エクスポート", import: "インポート", loading: "読み込み中...",
    noData: "データなし", confirm: "確認", back: "戻る", next: "次へ", submit: "送信",
    reset: "リセット", close: "閉じる", view: "表示", print: "印刷", download: "ダウンロード", upload: "アップロード",
    select: "選択", all: "すべて", none: "なし", yes: "はい", no: "いいえ", active: "アクティブ", inactive: "非アクティブ",
    pending: "保留中", completed: "完了", generalSettings: "一般設定", receiptSettings: "レシート設定",
    languageSettings: "言語設定", profileSettings: "プロフィール設定", appName: "アプリ名",
    appDescription: "説明", uploadLogo: "ロゴをアップロード", shopName: "店舗名", shopAddress: "住所",
    ownerNames: "オーナー名", addOwnerName: "オーナーを追加", phoneNumbers: "電話番号",
    addPhoneNumber: "電話番号を追加", thankYouMessage: "感謝メッセージ", footerMessage: "フッターメッセージ",
    workerName: "従業員名", workerPhone: "従業員電話", selectLanguage: "言語を選択",
    selectTimezone: "タイムゾーンを選択", saveGeneralSettings: "一般設定を保存",
    saveReceiptSettings: "レシート設定を保存", saveSettings: "設定を保存", saveProfile: "プロフィールを保存",
    fullName: "フルネーム", email: "メール", phoneNumber: "電話番号", items: "アイテム", total: "合計",
    invoiceDate: "請求日", paymentMethod: "支払い方法", cash: "現金", card: "カード", online: "オンライン",
    credit: "クレジット", discount: "割引", paidAmount: "支払い額", fullPayment: "全額払い",
    leaveEmptyForFullPayment: "全額払いの場合は空欄", saveAndPrint: "保存して印刷",
    customerName: "顧客名", customerPhone: "顧客電話", selectProduct: "商品を選択",
    quantity: "数量", price: "価格", subtotal: "小計", netTotal: "純計", totalCost: "総コスト",
    totalProfit: "総利益", finalTotal: "最終合計", paid: "支払い済み", due: "未払い", addProduct: "商品を追加",
    productName: "商品名", category: "カテゴリ", purchasePrice: "仕入れ価格", sellingPrice: "販売価格",
    stockQuantity: "在庫数", quantityType: "数量タイプ", supplier: "サプライヤー", sku: "SKU",
    description: "説明", lowStock: "在庫少", outOfStock: "在庫切れ", inStock: "在庫あり", addCredit: "クレジット追加",
    creditAmount: "クレジット額", remainingAmount: "残額", dueDate: "期限", status: "ステータス",
    notes: "メモ", paymentReceived: "支払い受領済み", markAsPaid: "支払い済みにする", addCustomer: "顧客を追加",
    customerDetails: "顧客詳細", totalPurchases: "総購入額", lastPurchase: "最終購入",
    addExpense: "経費を追加", expenseType: "経費タイプ", amount: "金額", date: "日付", rent: "家賃",
    utilities: "光熱費", salaries: "給与", supplies: "消耗品", other: "その他", addWorker: "従業員を追加",
    workerDetails: "従業員詳細", permissions: "権限", role: "役割", admin: "管理者", worker: "従業員",
    todaySales: "今日の売上", weeklySales: "週間売上", monthlySales: "月間売上",
    totalCustomers: "総顧客数", totalProducts: "総商品数", pendingCredits: "保留中クレジット",
    topProducts: "トップ商品", topCustomers: "トップ顧客", recentSales: "最近の売上",
    salesOverview: "売上概要", profitOverview: "利益概要", savedSuccessfully: "保存しました！",
    deletedSuccessfully: "削除しました！", errorOccurred: "エラーが発生しました", confirmDelete: "削除を確認しますか？",
    noPermission: "権限がありません", billNo: "請求番号", invoiceNo: "レシート番号", item: "アイテム", qty: "数量",
    today: "今日", yesterday: "昨日", thisWeek: "今週", thisMonth: "今月", lastMonth: "先月",
    custom: "カスタム", actions: "アクション", moreOptions: "その他のオプション",
  },
  // Korean
  ko: {
    dashboard: "대시보드", newInvoice: "새 청구서", inventory: "재고", salesHistory: "판매 내역",
    credits: "크레딧", creditManagement: "크레딧 관리", receivePayment: "결제 수령", expenses: "비용",
    customers: "고객", manageWorkers: "직원 관리", settings: "설정", logout: "로그아웃",
    collapse: "접기", save: "저장", cancel: "취소", delete: "삭제", edit: "편집", add: "추가",
    search: "검색", filter: "필터", export: "내보내기", import: "가져오기", loading: "로딩 중...",
    noData: "데이터 없음", confirm: "확인", back: "뒤로", next: "다음", submit: "제출",
    reset: "초기화", close: "닫기", view: "보기", print: "인쇄", download: "다운로드", upload: "업로드",
    select: "선택", all: "모두", none: "없음", yes: "예", no: "아니오", active: "활성", inactive: "비활성",
    pending: "보류 중", completed: "완료", generalSettings: "일반 설정", receiptSettings: "영수증 설정",
    languageSettings: "언어 설정", profileSettings: "프로필 설정", appName: "앱 이름",
    appDescription: "설명", uploadLogo: "로고 업로드", shopName: "상점 이름", shopAddress: "주소",
    ownerNames: "소유자 이름", addOwnerName: "소유자 추가", phoneNumbers: "전화번호",
    addPhoneNumber: "전화번호 추가", thankYouMessage: "감사 메시지", footerMessage: "푸터 메시지",
    workerName: "직원 이름", workerPhone: "직원 전화", selectLanguage: "언어 선택",
    selectTimezone: "시간대 선택", saveGeneralSettings: "일반 설정 저장",
    saveReceiptSettings: "영수증 설정 저장", saveSettings: "설정 저장", saveProfile: "프로필 저장",
    fullName: "성명", email: "이메일", phoneNumber: "전화번호", items: "항목", total: "합계",
    invoiceDate: "청구일", paymentMethod: "결제 방법", cash: "현금", card: "카드", online: "온라인",
    credit: "크레딧", discount: "할인", paidAmount: "결제 금액", fullPayment: "전액 결제",
    leaveEmptyForFullPayment: "전액 결제 시 비워두세요", saveAndPrint: "저장 후 인쇄",
    customerName: "고객 이름", customerPhone: "고객 전화", selectProduct: "상품 선택",
    quantity: "수량", price: "가격", subtotal: "소계", netTotal: "순계", totalCost: "총 비용",
    totalProfit: "총 이익", finalTotal: "최종 합계", paid: "결제됨", due: "미결제", addProduct: "상품 추가",
    productName: "상품명", category: "카테고리", purchasePrice: "구매가", sellingPrice: "판매가",
    stockQuantity: "재고 수량", quantityType: "수량 유형", supplier: "공급업체", sku: "SKU",
    description: "설명", lowStock: "재고 부족", outOfStock: "품절", inStock: "재고 있음", addCredit: "크레딧 추가",
    creditAmount: "크레딧 금액", remainingAmount: "잔액", dueDate: "마감일", status: "상태",
    notes: "메모", paymentReceived: "결제 수령", markAsPaid: "결제됨으로 표시", addCustomer: "고객 추가",
    customerDetails: "고객 상세", totalPurchases: "총 구매", lastPurchase: "마지막 구매",
    addExpense: "비용 추가", expenseType: "비용 유형", amount: "금액", date: "날짜", rent: "임대료",
    utilities: "공과금", salaries: "급여", supplies: "공급품", other: "기타", addWorker: "직원 추가",
    workerDetails: "직원 상세", permissions: "권한", role: "역할", admin: "관리자", worker: "직원",
    todaySales: "오늘 매출", weeklySales: "주간 매출", monthlySales: "월간 매출",
    totalCustomers: "총 고객", totalProducts: "총 상품", pendingCredits: "보류 중 크레딧",
    topProducts: "인기 상품", topCustomers: "인기 고객", recentSales: "최근 매출",
    salesOverview: "매출 개요", profitOverview: "이익 개요", savedSuccessfully: "저장 완료!",
    deletedSuccessfully: "삭제 완료!", errorOccurred: "오류 발생", confirmDelete: "삭제를 확인하시겠습니까?",
    noPermission: "권한 없음", billNo: "청구 번호", invoiceNo: "영수증 번호", item: "항목", qty: "수량",
    today: "오늘", yesterday: "어제", thisWeek: "이번 주", thisMonth: "이번 달", lastMonth: "지난 달",
    custom: "맞춤", actions: "작업", moreOptions: "더 많은 옵션",
  },
  // Italian, Dutch, Polish, Thai, Vietnamese, Indonesian, Malay, Bengali, Punjabi, Persian, Swahili, Tamil, Telugu, Marathi, Gujarati, Kannada, Malayalam, Ukrainian, Romanian, Greek, Czech, Swedish, Hungarian, Hebrew, Finnish, Norwegian, Danish - all use English as fallback
  it: {} as typeof translations.en,
  nl: {} as typeof translations.en,
  pl: {} as typeof translations.en,
  th: {} as typeof translations.en,
  vi: {} as typeof translations.en,
  id: {} as typeof translations.en,
  ms: {} as typeof translations.en,
  bn: {} as typeof translations.en,
  pa: {} as typeof translations.en,
  fa: {} as typeof translations.en,
  sw: {} as typeof translations.en,
  ta: {} as typeof translations.en,
  te: {} as typeof translations.en,
  mr: {} as typeof translations.en,
  gu: {} as typeof translations.en,
  kn: {} as typeof translations.en,
  ml: {} as typeof translations.en,
  uk: {} as typeof translations.en,
  ro: {} as typeof translations.en,
  el: {} as typeof translations.en,
  cs: {} as typeof translations.en,
  sv: {} as typeof translations.en,
  hu: {} as typeof translations.en,
  he: {} as typeof translations.en,
  fi: {} as typeof translations.en,
  no: {} as typeof translations.en,
  da: {} as typeof translations.en,
};

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: TranslationKey) => string;
  dir: "ltr" | "rtl";
  loading: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState("en");
  const [loading, setLoading] = useState(true);
  const [ownerId, setOwnerId] = useState<string | null>(null);

  useEffect(() => {
    const loadUserAndLanguage = async () => {
      try {
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) {
          setLoading(false);
          return;
        }

        const { data: roleData } = await supabase
          .from("user_roles")
          .select("role, admin_id")
          .eq("user_id", user.id)
          .single();

        const resolvedOwnerId = roleData?.role === "admin" ? user.id : roleData?.admin_id;
        setOwnerId(resolvedOwnerId || null);

        if (resolvedOwnerId) {
          const { data } = await supabase
            .from("app_settings")
            .select("language")
            .eq("owner_id", resolvedOwnerId)
            .maybeSingle();
          
          if (data?.language) {
            setLanguageState(data.language);
            // Update document direction
            const langConfig = LANGUAGES.find(l => l.code === data.language);
            if (langConfig) {
              document.documentElement.dir = langConfig.dir;
              document.documentElement.lang = data.language;
            }
          }
        }
      } catch (error) {
        console.error("Error loading language:", error);
      } finally {
        setLoading(false);
      }
    };
    
    loadUserAndLanguage();

    const { data: { subscription } } = supabase.auth.onAuthStateChange(() => {
      loadUserAndLanguage();
    });

    return () => subscription.unsubscribe();
  }, []);

  const setLanguage = async (lang: string) => {
    setLanguageState(lang);
    
    // Update document direction
    const langConfig = LANGUAGES.find(l => l.code === lang);
    if (langConfig) {
      document.documentElement.dir = langConfig.dir;
      document.documentElement.lang = lang;
    }
    
    if (!ownerId) return;
    
    try {
      await supabase
        .from("app_settings")
        .update({ language: lang } as any)
        .eq("owner_id", ownerId);
    } catch (error) {
      console.error("Error saving language:", error);
    }
  };

  const t = (key: TranslationKey): string => {
    const langTranslations = translations[language as keyof typeof translations] || translations.en;
    return langTranslations[key] || translations.en[key] || key;
  };

  const dir = LANGUAGES.find(l => l.code === language)?.dir === "rtl" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir, loading }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export default LanguageContext;
